{{- if eq .Values.profile.value "prod" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: chess-config
  namespace: {{ .Values.backend.nameSpace }}
data:
  db.service: {{ .Values.backend.env.db_service.value}}
  db.name: {{ .Values.backend.env.db_user.value}}
  db.user: {{ .Values.backend.env.db_name.value}}
{{- end }}  