{{- if .Values.profile.withPosgtre }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chess-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
{{- end }}        