apiVersion: v1
kind: Secret
metadata:
  name: chess-secret
  namespace: {{ .Values.backend.nameSpace }}
type: Opaque
data:
  db.user: {{ .Values.backend.env.db_user.value | b64enc}}
  db.pw: {{ .Values.backend.env.db_password.value | b64enc}}
