apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
        tier: backend
        track: stable
    spec:
      containers:
      - name: backend
        image: "udvaridonat/donat-chess:backend"
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        env:
        - name: DB_SERVICE
          valueFrom:
            configMapKeyRef:
              name: chess-config
              key: db.service
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: chess-config
              key: db.user
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: chess-config
              key: db.pw
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: chess-config
              key: db.name              