apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  selector:
    matchLabels:
      app: postgre
      tier: postgre
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: postgre
        tier: postgre
        track: stable
    spec:
      containers:
      - name: postgre
        image: "postgres:9.3"
        imagePullPolicy: Always
        env:
        - name: POSTGRES_USER
          value: "donat"        
        - name: POSTGRES_PASSWORD
          value: "don-chess-77"
        - name: POSTGRES_DB
          value: "donat"          
        ports:
        - name: http
          containerPort: 5432
