apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
        tier: frontend
        track: stable
    spec:
      containers:
      - name: nginx
        image: "udvaridonat/donat-chess:frontend"
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 4200