replicaCount: 1

nameSpace: chess

imagePullPolicy: Always

nodePort: 32123

backend:
    name: backend
    image: udvaridonat/donat-chess:backend
    port: 8080
    env:
        db_service:
            name: DB_SERVICE
            source: chess-config
            key: db.service
            value: postgre
        db_user:
            name: DB_USER
            source: chess-config
            key: db.user
            value: donat
        db_password:
            name: DB_PASSWORD
            source: chess-secret
            key: db.pw
            value: don-chess-77
        db_name:
            name: DB_NAME
            source: chess-config
            key: db.name
            value: donat
            
frontend:            
    name: frontend
    image: udvaridonat/donat-chess:frontend
    port: 4200
    
volume:
    path: /data/pvChess/
    
db:
    name: postgre
    port: 5432
    version: postgres:9.3
    mountPath: /var/lib/postgresql/data